/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#86a394",
        "outline-variant": "#d4c3c1",
        "secondary-container": "#e2dfde",
        "on-secondary-container": "#636262",
        "on-background": "#1b1c1c",
        "surface-container-highest": "#e4e2e2",
        "on-tertiary-fixed-variant": "#324c40",
        "surface-container-lowest": "#ffffff",
        tertiary: "#082319",
        "on-tertiary-fixed": "#052016",
        "inverse-surface": "#303031",
        "on-error": "#ffffff",
        primary: "#321716",
        "on-primary-fixed-variant": "#5f3e3c",
        "on-primary-container": "#bd928f",
        "surface-variant": "#e4e2e2",
        "secondary-fixed": "#e5e2e1",
        surface: "#fbf9f9",
        "secondary-fixed-dim": "#c8c6c5",
        "inverse-primary": "#eabcb8",
        "tertiary-fixed-dim": "#b0cdbe",
        "tertiary-container": "#1f392e",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#eabcb8",
        "on-surface": "#1b1c1c",
        secondary: "#5f5e5e",
        "tertiary-fixed": "#cbe9d9",
        "surface-container-high": "#e9e8e7",
        "surface-container-low": "#f5f3f3",
        "error-container": "#ffdad6",
        "on-surface-variant": "#504443",
        "primary-fixed": "#ffdad7",
        "inverse-on-surface": "#f2f0f0",
        "on-error-container": "#93000a",
        "surface-container": "#efeded",
        error: "#ba1a1a",
        "primary-container": "#4a2c2a",
        "surface-tint": "#795553",
        "on-primary-fixed": "#2e1413",
        "surface-dim": "#dbdad9",
        background: "#ffffff",
        "surface-bright": "#fbf9f9",
        "on-secondary-fixed-variant": "#474746",
        "on-secondary-fixed": "#1c1b1b",
        "on-primary": "#ffffff",
        outline: "#e0e0e0",
        "on-secondary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "0px",
      },
      spacing: {
        "stack-md": "40px",
        unit: "8px",
        "margin-desktop": "64px",
        "stack-lg": "120px",
        "stack-sm": "16px",
        gutter: "32px",
        "margin-mobile": "24px",
        "container-max": "1440px",
      },
      fontFamily: {
        "body-md": ["Hanken Grotesk"],
        "label-sm": ["Hanken Grotesk"],
        "display-lg-mobile": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
      },
      fontSize: {
        "body-md": [
          "16px",
          { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" },
        ],
        "display-lg-mobile": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "display-lg": [
          "88px",
          { lineHeight: "96px", letterSpacing: "-0.04em", fontWeight: "700" },
        ],
        "body-lg": [
          "20px",
          { lineHeight: "32px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
      },
      maxWidth: {
        "container-max": "1440px",
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-15px)' },
        },
        'float-delayed': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-15px)' },
        },
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        'spin-slow': {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        }
      },
      animation: {
        float: 'float 6s ease-in-out infinite',
        'float-delayed': 'float-delayed 6s ease-in-out infinite 3s',
        marquee: 'marquee 30s linear infinite',
        'spin-slow': 'spin-slow 12s linear infinite',
      },
    },
  },
  plugins: [],
};
